name: 'Post-Reaction CI to Docker Hub & Update K8s Manifest'

on:
  push:
    branches:
      - develop

env:
  DOCKERHUB_REPO: 'uniunity/post-reaction-service'
  K8S_REPO: 'https://github.com/Uniunity-msa/k8s.git'
  SERVICE_DIR: 'post-reaction-service'

jobs:
  docker:
    name: 'Build, Push Docker & Update K8s'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime, Asia/Seoul)
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Checkout K8s Repo
      uses: actions/checkout@v4
      with:
        repository: Uniunity-msa/k8s
        token: ${{ secrets.K8S_REPO_TOKEN }}
        path: k8s

    - name: Update kustomization.yaml
      run: |
        cd k8s/${{ env.SERVICE_DIR }}
        sed -i "s|image: ${{ env.DOCKERHUB_REPO }}:.*|image: ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}|" kustomization.yaml

    - name: Commit and Push Changes
      run: |
        cd k8s
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag: $IMAGE_TAG"
        git push
