name: 'Post CI to Docker Hub'

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: 'uniunity/post-service'
  K8S_REPO: 'https://github.com/Uniunity-msa/k8s.git'
  SERVICE_DIR: 'post-service'

jobs:
  docker:
    name: 'Build and Push to Docker Hub'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime)
      id: set-tag
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin

    - name: Clone K8s Repository
      run: |
        git clone https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/Uniunity-msa/k8s.git
        cd k8s/${{ env.SERVICE_DIR }}
        kustomize edit set image ${{ env.DOCKERHUB_REPO }}=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}

    - name: Commit and Push Image Tag Update
      run: |
        cd k8s
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag: $IMAGE_TAG" || echo "Nothing to commit"
        git push || echo "Nothing to push"
