name: 'Post-Reaction CI to Docker Hub'

on:
  push:
    branches:
      - develop

env:
  DOCKERHUB_REPO: 'uniunity/post-reaction-service'
  K8S_REPO: 'uniunity/k8s'  # k8s repo
  SERVICE_DIR: 'post-reaction-service'  # 서비스 이름과 동일한 폴더

jobs:
  docker:
    name: 'Build, Push and Auto-update K8s'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repo
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime)
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Clone K8s Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.K8S_REPO }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: k8s

    - name: Update kustomization.yaml with New Tag
      run: |
        cd k8s/${{ env.SERVICE_DIR }}
        kustomize edit set image ${{ env.DOCKERHUB_REPO }}=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}

    - name: Commit and Push to K8s Repository
      run: |
        cd k8s
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag: ${{ env.IMAGE_TAG }}"
        git push
